### ISSUE TITLE
how to install on windows os

### ISSUE THREAD

**Issue by windyslove** [nilium/ruby-glfw3#11]
E:\DemoWorkspace\opengl-> gem install glfw3
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing glfw3:
        ERROR: Failed to build gem native extension.

```
C:/Ruby/Ruby22/bin/ruby.exe -r ./siteconf20160903-9556-1c8soc4.rb extconf.rb
```

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/Ruby22/bin/$(RUBY_BASE_NAME)
extconf.rb:3:in ``': No such file or directory - pkg-config --static --libs glfw3 (Errno::ENOENT)
        from extconf.rb:3:in`<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/Ruby22/lib/ruby/gems/2.2.0/gems/glfw3-0.4.8 for inspection.
Results logged to C:/Ruby/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/glfw3-0.4.8/gem_make.out

i cant install this gem on windows , and how to install glfw3 and make it to be found by pkg-config

**Comment by nilium** [comment]
You'll have to install GLFW 3 from source, build it normally, etc. How that works out on Windows with pkg-config, I don't know. Basically, you're using Windows, so you're mostly on your own since I don't use it.

**Comment by windyslove** [comment]
thanks you
