### ISSUE TITLE
Add little "guide" on how to let pkg-config find glfw3

### ISSUE THREAD

**Issue by ghost** [nilium/ruby-glfw3#12]
I think you should add a little explanation on how to do this.

I tried now copying the "glfw-3.2.1" folder in every single path that has todo with pkg-config. I also tried renaming every folder to "glfw3". It did not worked.

Im on Windows.

**Comment by nilium** [comment]
I don’t know that Windows ever worked for this. It’s definitely not tested, so I can’t do much to help there.

On Linux and BSDs it’s fairly straightforward — you either install a package or build from source and things go where they need to. Not sure what one does for Windows. I suppose it’s possible it’d stop working if glfw dropped pkg-config but I’m not aware of that happening (haven’t done anything with this in years though).

**Comment by ghost** [comment]
hmm okay :/
