### ISSUE TITLE
Error installing the gem

### ISSUE THREAD

**Issue by Nogbit** [nilium/ruby-glfw3#3]
I installed GLFW per the [steps here](http://stackoverflow.com/questions/17768008/how-to-build-install-glfw-3-and-use-it-in-a-linux-project), but now I get the following errors when trying to install this gem.  Do you have any advice?

By the way, the [test program](http://www.glfw.org/docs/3.0/quick.html) from GLFW works just fine.

```
Building native extensions.  This could take a while...
ERROR:  Error installing glfw3:
    ERROR: Failed to build gem native extension.

    /home/marc/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling glfw3.c
glfw3.c: In function ‘rb_glfw_init’:
glfw3.c:85:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_monitor_position’:
glfw3.c:205:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_monitor_physical_size’:
glfw3.c:225:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_monitor_video_modes’:
glfw3.c:368:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c:375:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_monitor_video_mode’:
glfw3.c:396:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c:398:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_monitor_set_gamma_ramp’:
glfw3.c:513:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c: In function ‘rb_window_new’:
glfw3.c:667:28: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
glfw3.c: In function ‘rb_window_destroy’:
glfw3.c:685:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
glfw3.c:686:32: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
glfw3.c: In function ‘rb_monitor_get_gamma_ramp’:
glfw3.c:442:16: warning: ‘ramp’ is used uninitialized in this function [-Wuninitialized]
linking shared-object glfw3/glfw3.so
/usr/bin/ld: /usr/local/lib/libglfw3.a(context.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libglfw3.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [glfw3.so] Error 1
```

**Comment by nilium** [comment]
Tried doing what the linker error suggested? Can't really offer much since you haven't said what compiler you're using. I'm guessing this is on Linux though, in which case I'd be offering suggestions blind on fixing anything, so about all I can suggest is to do what the linker says and possibly tweak extconf.rb as needed.

I should also probably fix those warnings.

**Comment by Nogbit** [comment]
gcc version 4.7.3 

I edited the extconf.rb  to use -fPIC and I still get the same errors, I also tried the -shared but that didnt help.  However, I haven't monkeyed around with a gem install down at this level before so I'm probably doing something wrong.

```
require 'mkmf'

$LDFLAGS += " #{`pkg-config --static --libs glfw3`}"
$CFLAGS += " #{`pkg-config --cflags glfw3 -shared -fPIC`}"

create_makefile('glfw3/glfw3')
```

**Comment by nilium** [comment]
I'm not sure if the linker's asking you to rebuild GLFW3 with `-fPIC` or to add it to the compiler flags for ruby-glfw3, but adding anything as a flag passed to pkg-config isn't going to do much of anything other than break the flags — so, keep in mind where you're putting flags.

**Comment by Nogbit** [comment]
I wasn't able to ascertain that either, GLFW3 does build fine and a test of it worked as well.

**Comment by Nogbit** [comment]
It must be with GLFW3 not the gem.  By the way, I noticed $CFLAGS already has -fPIC in it.  If I remove it I still get the same errors or if I add in -shared (correctly this time, thanks) the same errors occur.  I will try to recompile GLFW3 now.

**Comment by Nogbit** [comment]
I'm all set now, it was GLFW3 that needed -fPIC.  This gem compiled and the demo on the readme loaded.  Thanks!

add line 88 of glfw-3.0.3/CMakeLists.txt
`add_definitions(-fPIC)`

then

```
cmake -G "Unix Makefiles"
make
sudo make install
```

**Comment by nilium** [comment]
In that case, I'll go ahead and close this.
