### ISSUE TITLE
video_modes causes segfault

### ISSUE THREAD

**Issue by jstenhouse** [nilium/ruby-glfw3#6]
Trying to run `Glfw::Monitor.primary_monitor.video_modes` in Ruby versions 2.1.1, 2.1.0, and 2.0.0-p451 causes a segfault for me on OS X 10.9.2

The code I'm using is here: https://gist.github.com/jstenhouse/1d4daca90b7cbe4262f3

If you want the segfault let me know.

**Comment by nilium** [comment]
I want anything to do with the segfault, particularly anything with a stack trace.

**Comment by jstenhouse** [comment]
I updated the gists for this and gammaramp issues with the crash reports. Thanks!

**Comment by jstenhouse** [comment]
:+1:
